# Generated by Django 3.1.2 on 2020-10-17 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Post.post')),
                ('video', models.FileField(upload_to='videos/')),
            ],
            bases=('Post.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
